# Welcome to Jekyll!
#

# Site settings
title: Horv치th Dominik
description: |
  PHP Developer
owner: Horv치th Dominik # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: djsmemories@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dominikh.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/djsmemories
  github: https://github.com/djsmemories
  linkedin-square: https://linkedin.com/in/dominik-horv치th-45a81062
  facebook-official: https://facebook.com/ffhtc
  google-plus-square: https://plus.google.com/u/0/+DominikHorv치thHungary
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
