# Welcome to Jekyll!
#

# Site settings
title: Refresh Austin
description: |
  We are a community of designers and developers working to refresh the creative, technical, and professional culture of New Media endeavors in their areas. Promoting design, technology, usability, and standards.
owner: Refresh Austin # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: info@refreshaustin.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://refreshaustin.github.io/spectral" # the base hostname & protocol for your site

social:
  twitter: https://twitter.com/refreshaustin
  # linkedin-square: https://linkedin.com/in/<username>
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
future: true
